apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  namespace: franklyn
data:
  POSTGRES_DB: db
  POSTGRES_USER: app
---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: franklyn
type: Opaque
stringData:
  POSTGRES_PASSWORD: app
