# franklyn-server
apiVersion: apps/v1
kind: Deployment
metadata:
  name: franklyn-server
  namespace: franklyn
spec:
  selector:
    matchLabels:
      app: franklyn-server
  template:
    metadata:
      labels:
        app: franklyn-server
    spec:
      containers:
        - image: docker.io/library/franklyn-server:latest
          name: franklyn-server
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: franklyn-server-service
  namespace: franklyn
spec:
  selector:
    app: franklyn-server
  ports:
    - port: 8080
      targetPort: 8080
  type: ClusterIP
