apiVersion: apps/v1
kind: Deployment
metadata:
  name: franklyn-proctor
spec:
  selector:
    matchLabels:
      app: franklyn-proctor
  template:
    metadata:
      labels:
        app: franklyn-proctor
    spec:
      containers:
        - name: franklyn-proctor
          # TODO: use ghcr.io
          image: docker.io/jakkki/franklyn-proctor:latest
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: franklyn-proctor-service
spec:
  selector:
    app: franklyn-proctor
  ports:
    - port: 80
      targetPort: 80
  type: ClusterIP
