apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: franklyn-ingress
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: franklyn-server-service
                port:
                  number: 8080
          - path: /proctor
            pathType: prefix
            backend:
              service:
                name: franklyn-proctor-service
                port:
                  number: 80
          - path: /
            pathType: Prefix
            backend:
              service:
                name: franklyn-hugo-service
                port:
                  number: 80
