baseURL: ''
languageCode: en
title: Franklyn

enableGitInfo: true

defaultContentLanguage: en

outputs:
  home: [html, llms]
  page: [html, markdown]
  section: [html, markdown]

module:
  imports:
    - path: github.com/imfing/hextra

markup:
  goldmark:
    renderer:
      unsafe: true
