main:
  - name: Documentation
    pageRef: /docs
    weight: 1
  - name: Guide
    pageRef: /guide
    weight: 2
  - identifier: proctor
    name: Proctor
    pageRef: /proctor
    weight: 3
  - name: Search
    weight: 5
    params:
      type: search
  - name: GitHub
    weight: 6
    url: "https://github.com/2526-4ahitm-itp/2526-4ahitm-franklyn"
    params:
      icon: github