# franklyn-server
apiVersion: apps/v1
kind: Deployment
metadata:
  name: franklyn-server
spec:
  selector:
    matchLabels:
      app: franklyn-server
  template:
    metadata:
      labels:
        app: franklyn-server
    spec:
      containers:
        # TODO: change to ghcr.io
        - image: docker.io/jakkki/franklyn-server:latest
          imagePullPolicy: Always
          name: franklyn-server
          ports:
            - containerPort: 8080
          env:
            - name: QUARKUS_DATASOURCE_JDBC_URL
              value: jdbc:postgresql://postgres-service:5432/${DB_NAME}
            - name: QUARKUS_DATASOURCE_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: postgres-config
                  key: POSTGRES_USER
            - name: QUARKUS_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: postgres-password
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: postgres-config
                  key: POSTGRES_DB
---
apiVersion: v1
kind: Service
metadata:
  name: franklyn-server-service
spec:
  selector:
    app: franklyn-server
  ports:
    - port: 8080
      targetPort: 8080
  type: ClusterIP
