apiVersion: apps/v1
kind: Deployment
metadata:
  name: franklyn-hugo
spec:
  selector:
    matchLabels:
      app: franklyn-hugo
  template:
    metadata:
      labels:
        app: franklyn-hugo
    spec:
      containers:
        - name: franklyn-hugo
          imagePullPolicy: Always
          image: docker.io/jakkki/franklyn-hugo:latest
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: franklyn-hugo-service
spec:
  selector:
    app: franklyn-hugo
  ports:
    - port: 80
      targetPort: 80
  type: ClusterIP
