services:
  postgres:
    extends:
      file: ./postgres.yaml
      service: postgres

  pgadmin:
    extends:
      file: ./postgres.yaml
      service: pgadmin

  keycloak:
    extends:
      file: ./keycloak.yaml
      service: keycloak

volumes:
  franklyn-postgres-database:
  franklyn-pgadmin4-servers:
  franklyn-keycloak-data:


networks:
  franklyn-network:
    driver: bridge
