services:
  keycloak:
    image: quay.io/keycloak/keycloak:26.4.6
    container_name: keycloak
    restart: always
    command:
        - start-dev 
    ports:
      - "7070:8080"
    networks:
      - franklyn-network
    volumes:
      - franklyn-keycloak-data:/opt/keycloak/data

volumes:
  franklyn-keycloak-data:

networks:
  franklyn-network:
    external: true
