services:
  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: keycloak-dev
    environment:
      # Admin credentials
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
      
      # Development mode settings
      KC_HEALTH_ENABLED: 'true'
      KC_METRICS_ENABLED: 'true'
    
    command:
      - start-dev
      - --import-realm
    
    volumes:
      - franklyn-keycloak-data:/opt/keycloak/data
      - ./realm-config.json:/opt/keycloak/data/import/realm-config.json:ro
    
    ports:
      - "7070:8080"
    
    healthcheck:
      test: ["CMD-SHELL", "exec 3<>/dev/tcp/127.0.0.1/8080;echo -e 'GET /health/ready HTTP/1.1\r\nhost: http://localhost\r\nConnection: close\r\n\r\n' >&3;if [ $? -eq 0 ]; then echo 'Healthcheck Successful';exit 0;else echo 'Healthcheck Failed';exit 1;fi;"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 90s

    
    networks:
      - franklyn-network

volumes:
  franklyn-keycloak-data:
