services:
  keycloak:
    image: quay.io/keycloak/keycloak:26.4.4
    container_name: keycloak
    restart: always
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin 
    command:
        - start-dev 
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    networks:
      - franklyn-network
    volumes:
      - franklyn-keycloak-data:/opt/keycloak/data

volumes:
  franklyn-keycloak-data:

networks:
  franklyn-network:
    external: true
