[package]
name = "franklyn-sentinel"
version = "0.0.0"
edition = "2024"

[dependencies]
ffmpeg-next = "8.0.0"
xcap = "0.7.1"


[features]
wayland-recording = []

[lints.clippy]
correctness = "deny"
suspicious = "deny"
perf = "deny"
nursery = "warn"