name: ğŸš€ Deploy Docs

on:
  workflow_dispatch:
  push:
    paths:
      - hugo/**
    branches:
      - main
      - ci/deploy*

permissions:
  contents: read
  pages: write
  packages: write
  id-token: write

jobs:
  build-hugo:
    name: ğŸ—ï¸ Build Hugo
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: â„ï¸ Setup Nix
        uses: ./.github/actions/setup-nix
        with:
          environment: hugo
          cachix_auth_token: ${{ secrets.CACHIX_AUTH_TOKEN }}

      - name: ğŸ“„ Setup Pages
        id: pages
        uses: actions/configure-pages@v5

      - name: ğŸ”¨ Build Hugo (GitHub Pages)
        run: |
          cd hugo
          export HUGO_CACHE_DIR="${{ runner.temp }}/hugo_cache"
          export HUGO_BASE_URL="${{ steps.pages.outputs.base_url }}/"
          nix develop .#hugo --command fr-hugo-build --baseURL $HUGO_BASE_URL --cacheDir $HUGO_CACHE_DIR

      - name: ğŸ”¨ Build Hugo (Docker)
        run: |
          cd hugo
          export HUGO_CACHE_DIR="${{ runner.temp }}/hugo_cache"
          nix develop .#hugo --command fr-hugo-build --cacheDir $HUGO_CACHE_DIR --destination public-docker

      - name: ğŸ”‘ Login to ghcr.io
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: ğŸ³ Build and Push Hugo
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./hugo/docker/Dockerfile.ci
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/franklyn-hugo:latest
            ghcr.io/${{ github.repository_owner }}/franklyn-hugo:${{ github.sha }}

      - name: ğŸ“¦ Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./hugo/public

  deploy-hugo:
    if: github.ref == 'refs/heads/main'
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    name: ğŸš€ Deploy Hugo
    runs-on: ubuntu-latest
    needs: build-hugo
    steps:
      - name: ğŸŒ Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
